yuuki-foll/Grow-plants-web-app

README.md

[update]#1 venvの説明

---

codes/breed_server.go
codes/templates/breed_plant_main.html.tpl

[add] homepage

---

codes/templates/breed_plant.html.tpl

[add]#1 ring_BGM

---

codes/templates/breed_plant.html.tpl

fix conflict

---

codes/static/css/breed_plant.css
codes/static/js/breed_plant.js
codes/templates/breed_plant.html.tpl

add css&js

---

codes/breed_server.go
codes/static/css/breed_plant.css
codes/static/js/breed_plant.js
codes/templates/breed_plant.html.tpl

link & fix css&js

---

codes/static/css/breed_plant.css
codes/static/js/breed_plant.js
codes/templates/breed_plant.html.tpl

changeable life bar color

---

codes/breed_server.go
codes/templates/after.html
codes/templates/breed_plant.html.tpl
codes/templates/breed_plant_main.html.tpl

[Update]  on login 
[Change] UI for bgm

update on login & ui change for bgm

---

codes/static/css/breed_plant.css
codes/templates/breed_plant.html.tpl

add se & upgrade background

---

codes/breed_server.go

[add]#1 データのセーブ機能

---

codes/breed_server.go

[update]#1 secretkey修正

---

codes/static/css/breed_plant.css

add background

---

codes/static/css/breed_plant.css
codes/templates/breed_plant.html.tpl

add titleback

---

codes/breed_server.go

ログイン時にセーブデータがあればセーブデータをfirebaseから取得する

[add] #1 load data

---

codes/breed_server.go

[update] #2 secretkey修正

---

codes/breed_server.go
codes/templates/breed_plant.html.tpl

認証時に/page0にcookieでセーブデータを送りフロントでcookieを読み込む

[update] #1 loaddata

---

codes/breed_server.go
codes/templates/after.html
codes/templates/breed_plant.html.tpl

logout機能実装（logout時にcookie削除）
gestモード時にafterに飛ばないように変更（cookieがなくてエラーになるから）

[add]#1 logout

---

codes/breed_server.go
codes/templates/breed_plant.html.tpl

change image

---

codes/static/css/login.css
codes/templates/login.html

[update]#1 loginpage

---

codes/static/css/home.css
codes/templates/breed_plant.html.tpl
codes/templates/breed_plant_main.html.tpl

[update]#1 homepage

---

codes/static/js/page0.js

update function when plant dead

---

codes/static/css/breed_plant.css
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

[add]#44 new mute button

---

codes/breed_server.go
codes/static/js/page0.js

植物をデータベースに保存、ロードなど
チューリップでsaveするとチューリップで再開

[update]#47 seed saved

---

codes/static/js/page0.js

[update]#50 fix load img

---

codes/static/css/login.css
codes/templates/login.html

add login image

---

codes/breed_server.go

新規ユーザーが開始すると体力が0スタートになってしまっていたのを修正

[fix]#52 new user start

---

codes/breed_server.go
codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

ゲストモードまたは植物を選んでない時にモーダルウィンドウを表示させる

[add]#53 modal window

---

codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/templates/breed_plant.html.tpl

[add]#58 modal new button

---

codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

add some plants

---

codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/templates/breed_plant.html.tpl

[update]#60 modal select plants

---

codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/templates/breed_plant.html.tpl

[add]#62 picture-book base

---

codes/breed_server.go

[add]#65 new_database

---

codes/static/css/breed_plant.css
codes/static/js/micromodal.js

モーダルウィンドウのimgサイズの変更
追加の植物を選択できるように修正

[fix]#66 modal picsize

---

codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

Feature/plant UI

---

codes/static/js/breed_plant.js
codes/static/js/micromodal.js
codes/static/js/page0.js

chane img size by seed_name

---

codes/breed_server.go
codes/static/js/page0.js

植物が育ちきったら植物の名前がTrueになったjsonをpostする

[add] pictbook post

---

codes/breed_server.go
codes/static/js/page0.js

植物を育てきったときの情報をデータベースに保存するようにした
usernameもフロントからとってくるように変えた

[add]#69 picture book info save database

---

codes/breed_server.go
codes/static/js/page0.js

ログイン時に植物図鑑のデータをデータベースに取得
クッキーにセット

[add] load pictbook info

---

codes/static/css/breed_plant.css
codes/static/js/breed_plant.js
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

add effect for plant.

---

codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/templates/breed_plant.html.tpl

[update] new pict book UI

---

codes/static/js/breed_plant.js
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

add death_bgm & damage_se

---

codes/static/js/page0.js

fix damage_value

---

codes/breed_server.go
codes/static/js/micromodal.js
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

植物追加対応
植物図鑑　・育てた　→表示
　　　　　・まだ　→　鉢

[update] picture book

---

codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/templates/breed_plant.html.tpl

[add] new image

---

codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

[add] result modal

---

codes/static/js/micromodal.js
codes/templates/breed_plant.html.tpl

[add] tweet func

---

codes/breed_server.go
codes/static/css/breed_plant.css
codes/static/js/micromodal.js
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

[add] rose and pansy

---

codes/static/js/choice_color.js
codes/static/js/page0.js

update flower color

---

codes/static/css/breed_plant.css
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

メインページのUI修正
・感情分析結果の背景色
・漢字→ひらがな
・上のボタンの位置、大きさ変更
・タイトルの文字を変更

[update] maintenance UI

---

codes/static/js/micromodal.js

update get plant explanation

---

codes/static/css/breed_plant.css
codes/static/js/breed_plant.js
codes/templates/breed_plant.html.tpl

メイン画面・図鑑などのフォント・フォントサイズを変更
最初の植物を選ぶ画面で植物を変更すると画像が切り替わるように修正
--コンフリクトを修正--

Feature/update UI

---

codes/breed_server.go
codes/static/js/page0.js

植物のカラーのデータをfirebaseにユーザーネームと一緒に保存するための準備を行った。
新しいユーザがログインしたときにすべての色のデータをfalseにしてfirebaseに保存
ログイン時firebaseを読み込みpage0に色のデータをcookieに保存
jsでstringを展開しboolにして配列に保存

register and load plants color data

---

codes/templates/breed_plant.html.tpl

change arrow in picture book

---

codes/breed_server.go
codes/static/js/choice_color.js
codes/static/js/micromodal.js
codes/static/js/page0.js

花が咲いたとき色をjsonで送信しデータベースに保存
植物図鑑で育てない色は黒〇に変更

add color variation save firebase

---

codes/static/js/mainpage.js
codes/templates/after.html
codes/templates/breed_plant_main.html.tpl

タイトル画面のボタンの挙動を修正
（htmlからurlを指定してページ遷移していたのをjavascriptで現在のurlを取得して遷移するように変更）

fix main_page buttom function

---

codes/static/css/breed_plant.css
codes/static/js/breed_plant.js
codes/static/js/micromodal.js
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

タネをかえるボタンを押す→最初にページを開いたときと同じモーダルを表示
モーダルを閉じるときに、体力,senti_level,ハートを初期状態に戻す。
breed_plantの<slect>を削除

update pick plants

---

codes/breed_server.go
codes/static/js/choice_color.js
codes/static/js/page0.js

max状態でチューリップ、バラ、コスモス、パンジーを保存する際に、花の色も保存。
choiceImageの引数にbool型を追加しデータload時にはランダムで色を選ばせないように実装

save時に花の色を保存する

---

codes/templates/breed_plant.html.tpl

植物選択モーダルの表示変更

---

codes/static/css/breed_plant.css
codes/static/css/home.css
codes/static/css/login.css
codes/templates/after.html
codes/templates/breed_plant_main.html.tpl
codes/templates/login.html

fontをpage0と同じように変更
漢字からひらがなに変更
難しそうな表現を簡単な日本語に変えてみた

ログインページ、メインページのUI修正

---

codes/static/css/breed_plant.css
codes/static/js/page0.js
codes/templates/breed_plant.html.tpl

話しかけるボタンを押すとモーダル表示
話しかけ終わるとモーダル削除
モーダルの中身
録音中
変なアニメーション

録音中が分かるように可視化

---

codes/static/css/breed_plant.css
codes/templates/breed_plant.html.tpl

結果画面のボタン
閉じる→とじる
twitterで共有→ツイートする
文字フォント、文字サイズをほかのボタンと同じに修正

結果画面のボタンのデザイン修正

---

codes/static/js/micromodal.js

パンジーの画像差し替えの関数間違えてました。
植物を選択しなかったのに初期化されてしまう
変数置いて植物を選択したときtrueにして
trueの時だけ初期化するように変更

[fix]#119　植物をかえるときの挙動の修正 

---

codes/static/js/page0.js

change secret word
